name: Run tests
on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Build code
        run: yarn build
      - name: Run tests
        run: yarn test
